<a href="https://colab.research.google.com/github/NooshinS/Machine-Learning/blob/main/A_N_N.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Artificial Neural Network for Predicting If a Customer Leaves the Bank or Not?**

Importing Libraries

In [33]:
import pandas as pd
import numpy as np
import tensorflow as tf

Data Preprocessing

Import the Dataset

In [34]:
dataset=pd.read_csv('Churn_Modelling.csv')
x=dataset.iloc[:, 3:-1].values
y=dataset.iloc[:, -1].values
print(x)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


Encoding

In [35]:
#Lable Encoding Gender Column
from sklearn.preprocessing import LabelEncoder
Le=LabelEncoder()
x[:, 2]=Le.fit_transform(x[:, 2])
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [36]:
#Encoding the Categorical Data Geography Column
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
CT=ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x=np.array(CT.fit_transform(x))
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

Splitting the Data into the train and test set

In [37]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split (x,y, test_size=0.2, random_state=0) 

Feature Scaling

In [38]:
from sklearn.preprocessing import StandardScaler
SC=StandardScaler()
x_train=SC.fit_transform(x_train)
x_test=SC.transform(x_test)

Building the ANN Model

In [39]:
ann=tf.keras.models.Sequential()

Adding the Input layesr and the Hidden Layer

In [40]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the Second Layer

In [41]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the Output Layer

In [42]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

Training The ANN

Compiling the ANN

In [43]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics= ['accuracy'])

Training the Ann Model on the Traning Set

In [44]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6180 - accuracy: 0.6482
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4798 - accuracy: 0.7928
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4523 - accuracy: 0.7952
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4404 - accuracy: 0.7954
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4333 - accuracy: 0.7989
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4281 - accuracy: 0.8019
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4218 - accuracy: 0.8077
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4146 - accuracy: 0.8120
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4058 - accuracy: 0.8195
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3963 - accura

In [46]:
#Prediction
print(ann.predict(SC.transform([[1,0,0,600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))>0.5)

[[False]]


Predicting the Test Results

In [47]:
#Predicting
y_pred=ann.predict(x_test)
y_pred=(y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making Confusion Matrix

In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score
CM= confusion_matrix (y_test, y_pred)
print(CM) 
accuracy_score (y_test, y_pred)

[[1512   83]
 [ 197  208]]


0.86